version: "3.3"
services:
  mariadb:
    restart: always
    image: mariadb:10.2
    ports:
      - "127.0.0.1:3306:3306"     #Local
    environment:
      - MYSQL_ROOT_PASSWORD=<TODO:mysql_root_password_here>
      - MYSQL_DATABASE=pdns
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD=<TODO:pdns_user_password_here>
    volumes:
      - type: volume              #MySQL Database
        source: mariadb-data
        target: /var/lib/mysql
  pdns-server:
    restart: always
    image: psitrax/powerdns:4.1.4
    ports:
      - "53:53"                   #Public
      - "53:53/udp"               #Public
      - "127.0.0.1:8081:8081"     #Local
    environment:
      - MYSQL_AUTOCONF=false      #Because we are overriding the conf file
    volumes:
      - type: bind
        source: ./pdns.conf
        target: /etc/pdns/pdns.conf
volumes:
  mariadb-data:
    external: true
  nsedit-data:
    external: true
