version: "3.3"
services:
  mariadb:
    restart: always
    image: 10.27.252.185/mariadb:10.2
#    networks:
#      - pdns-net
    ports:
      - "127.0.0.1:3306:3306"     #Local
    environment:
      - MYSQL_ROOT_PASSWORD="Dncl_lsk456&df"
      - MYSQL_DATABASE=pdns
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD=password
    volumes:
      - type: volume
        source: mariadb-data
        target: /var/lib/mysql
  pdns-server:
    restart: always
    image: 10.27.252.185/powerdns:psitrax-4.1.0
#    networks:
#      - pdns-net
    ports:
      - "53:53"                   #Public
      - "53:53/udp"               #Public
      - "127.0.0.1:8081:8081"     #Local
    environment:
      - MYSQL_AUTOCONF=false
    volumes:
      - type: bind
        source: ./pdns.conf
        target: /etc/pdns/pdns.conf
  nsedit:
    restart: always
    image: 10.27.252.185/nsedit-debian:jessie-1.1
    ports:
      - "80:8080"                 #Public
    volumes:
      - type: bind
        source: ./config.inc.php
        target: /app/nsedit/includes/config.inc.php
      - type: volume                #NSEdit Sqlite Database
        source: nsedit-data
        target: /app/data
volumes:
  mariadb-data:
    external: true
  nsedit-data:
    external: true
#networks:
#  pdns-net:

